allowBuilds:
  "@whiskeysockets/baileys": true
  better-sqlite3: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

overrides:
  "@esbuild-kit/core-utils>esbuild": 0.25.12
  ip-address: 10.3.1
  nanoid: 3.3.18
  next>sharp: 0.35.3
  postcss: 8.5.23
  sharp: 0.35.3
