import type { RentalLocation } from "../rental-locations";

/** Initial asset placement used only when a fresh database is seeded. */
export const bikeOptionsByLocation = {
  munich: [
    "Endurace CF SL 8 - XS",
    "Endurace CF SL 8 - S",
    "Endurace CF SL 8 - S",
    "Endurace CF SL 8 - M",
    "Endurace CF SL 8 - M",
    "Endurace CF SL 8 - L",
    "Grail CF SL 7 - S",
    "Grail CF SL 7 - M",
    "Grail CF SL 7 - L",
    "Ultimate CF SL 7 - M",
    "Ultimate CF SL 7 - L",
    "Aeroad CF SL 8 - S",
    "Aeroad CF SL 8 - M",
  ],
  regensburg: [
    "Endurace CF SL 8 - XS",
    "Endurace CF SL 8 - S",
    "Endurace CF SL 8 - M",
    "Endurace CF SL 8 - L",
    "Grail CF SL 7 - S",
    "Grail CF SL 7 - M",
    "Grail CF SL 7 - L",
  ],
  lindau: [
    "Endurace CF SL 8 - XS",
    "Endurace CF SL 8 - S",
    "Endurace CF SL 8 - M",
    "Endurace CF SL 8 - L",
    "Grail CF SL 7 - S",
    "Grail CF SL 7 - M",
    "Grail CF SL 7 - L",
  ],
  friedrichshafen: [
    "Endurace CF SL 8 - XS",
    "Endurace CF SL 8 - S",
    "Endurace CF SL 8 - M",
    "Endurace CF SL 8 - L",
    "Grail CF SL 7 - S",
    "Grail CF SL 7 - M",
    "Grail CF SL 7 - L",
  ],
  konstanz: [
    "Endurace CF SL 8 - XS",
    "Endurace CF SL 8 - S",
    "Endurace CF SL 8 - M",
    "Endurace CF SL 8 - L",
    "Grail CF SL 7 - S",
    "Grail CF SL 7 - M",
    "Grail CF SL 7 - L",
  ],
} as const satisfies Record<RentalLocation, readonly string[]>;
